[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = [".", "--output-dir", "./static/css"]

#[[hooks]]
#stage = "pre_build"
#command = "leptosfmt"
#command_arguments = ["./src/**/*.rs"]

[watch]
ignore = ["static"]